/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'canvas.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./canvas.android-arm64.node')
          } else {
            nativeBinding = require('canvas-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'canvas.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./canvas.android-arm-eabi.node')
          } else {
            nativeBinding = require('canvas-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'canvas.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canvas.win32-x64-msvc.node')
          } else {
            nativeBinding = require('canvas-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'canvas.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canvas.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('canvas-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'canvas.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canvas.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('canvas-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'canvas.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./canvas.darwin-universal.node')
      } else {
        nativeBinding = require('canvas-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'canvas.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./canvas.darwin-x64.node')
          } else {
            nativeBinding = require('canvas-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'canvas.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canvas.darwin-arm64.node')
          } else {
            nativeBinding = require('canvas-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'canvas.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./canvas.freebsd-x64.node')
      } else {
        nativeBinding = require('canvas-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'canvas.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canvas.linux-x64-musl.node')
            } else {
              nativeBinding = require('canvas-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'canvas.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canvas.linux-x64-gnu.node')
            } else {
              nativeBinding = require('canvas-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'canvas.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canvas.linux-arm64-musl.node')
            } else {
              nativeBinding = require('canvas-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'canvas.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canvas.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('canvas-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        localFileExisted = existsSync(
          join(__dirname, 'canvas.linux-arm-gnueabihf.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canvas.linux-arm-gnueabihf.node')
          } else {
            nativeBinding = require('canvas-linux-arm-gnueabihf')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { Canvas, LineCap, FillRule, PixelFormat, CanvasGradient, LineJoin, AliasingMode, GlobalCompositeOperation, CanvasRenderingContext2D, createCanvas, createImageData, DomMatrix, ImageData, PngFilters, Image, ImageKind, ImageMode, Quality, Repetition, TextAlign, TextBaseline, TextDrawingMode } = nativeBinding

module.exports.Canvas = Canvas
module.exports.LineCap = LineCap
module.exports.FillRule = FillRule
module.exports.PixelFormat = PixelFormat
module.exports.CanvasGradient = CanvasGradient
module.exports.LineJoin = LineJoin
module.exports.AliasingMode = AliasingMode
module.exports.GlobalCompositeOperation = GlobalCompositeOperation
module.exports.CanvasRenderingContext2D = CanvasRenderingContext2D
module.exports.createCanvas = createCanvas
module.exports.createImageData = createImageData
module.exports.DomMatrix = DomMatrix
module.exports.ImageData = ImageData
module.exports.PngFilters = PngFilters
module.exports.Image = Image
module.exports.ImageKind = ImageKind
module.exports.ImageMode = ImageMode
module.exports.Quality = Quality
module.exports.Repetition = Repetition
module.exports.TextAlign = TextAlign
module.exports.TextBaseline = TextBaseline
module.exports.TextDrawingMode = TextDrawingMode

module.exports.DOMMatrix = DomMatrix;