// This is a manually written file for the C API of unicode.zig
// TODO: delete this when Zig resurrects -femit-h
// https://github.com/ziglang/zig/issues/9698
#pragma once

#include <cstdint>
#include <hb.h>

typedef enum {
  SCRIPT_NONE,
  SCRIPT_ADLAM,
  SCRIPT_AHOM,
  SCRIPT_ANATOLIAN_HIEROGLYPHS,
  SCRIPT_ARABIC,
  SCRIPT_ARMENIAN,
  SCRIPT_AVESTAN,
  SCRIPT_BALINESE,
  SCRIPT_BAMUM,
  SCRIPT_BASSA_VAH,
  SCRIPT_BATAK,
  SCRIPT_BENGALI,
  SCRIPT_BHAIKSUKI,
  SCRIPT_BOPOMOFO,
  SCRIPT_BRAHMI,
  SCRIPT_BRAILLE,
  SCRIPT_BUGINESE,
  SCRIPT_BUHID,
  SCRIPT_CANADIAN_ABORIGINAL,
  SCRIPT_CARIAN,
  SCRIPT_CAUCASIAN_ALBANIAN,
  SCRIPT_CHAKMA,
  SCRIPT_CHAM,
  SCRIPT_CHEROKEE,
  SCRIPT_CHORASMIAN,
  SCRIPT_COMMON,
  SCRIPT_COPTIC,
  SCRIPT_CUNEIFORM,
  SCRIPT_CYPRIOT,
  SCRIPT_CYPRO_MINOAN,
  SCRIPT_CYRILLIC,
  SCRIPT_DESERET,
  SCRIPT_DEVANAGARI,
  SCRIPT_DIVES_AKURU,
  SCRIPT_DOGRA,
  SCRIPT_DUPLOYAN,
  SCRIPT_EGYPTIAN_HIEROGLYPHS,
  SCRIPT_ELBASAN,
  SCRIPT_ELYMAIC,
  SCRIPT_ETHIOPIC,
  SCRIPT_GARAY,
  SCRIPT_GEORGIAN,
  SCRIPT_GLAGOLITIC,
  SCRIPT_GOTHIC,
  SCRIPT_GRANTHA,
  SCRIPT_GREEK,
  SCRIPT_GUJARATI,
  SCRIPT_GUNJALA_GONDI,
  SCRIPT_GURMUKHI,
  SCRIPT_GURUNG_KHEMA,
  SCRIPT_HAN,
  SCRIPT_HANGUL,
  SCRIPT_HANIFI_ROHINGYA,
  SCRIPT_HANUNOO,
  SCRIPT_HATRAN,
  SCRIPT_HEBREW,
  SCRIPT_HIRAGANA,
  SCRIPT_IMPERIAL_ARAMAIC,
  SCRIPT_INHERITED,
  SCRIPT_INSCRIPTIONAL_PAHLAVI,
  SCRIPT_INSCRIPTIONAL_PARTHIAN,
  SCRIPT_JAVANESE,
  SCRIPT_KAITHI,
  SCRIPT_KANNADA,
  SCRIPT_KATAKANA,
  SCRIPT_KAWI,
  SCRIPT_KAYAH_LI,
  SCRIPT_KHAROSHTHI,
  SCRIPT_KHITAN_SMALL_SCRIPT,
  SCRIPT_KHMER,
  SCRIPT_KHOJKI,
  SCRIPT_KHUDAWADI,
  SCRIPT_KIRAT_RAI,
  SCRIPT_LAO,
  SCRIPT_LATIN,
  SCRIPT_LEPCHA,
  SCRIPT_LIMBU,
  SCRIPT_LINEAR_A,
  SCRIPT_LINEAR_B,
  SCRIPT_LISU,
  SCRIPT_LYCIAN,
  SCRIPT_LYDIAN,
  SCRIPT_MAHAJANI,
  SCRIPT_MAKASAR,
  SCRIPT_MALAYALAM,
  SCRIPT_MANDAIC,
  SCRIPT_MANICHAEAN,
  SCRIPT_MARCHEN,
  SCRIPT_MASARAM_GONDI,
  SCRIPT_MEDEFAIDRIN,
  SCRIPT_MEETEI_MAYEK,
  SCRIPT_MENDE_KIKAKUI,
  SCRIPT_MEROITIC_CURSIVE,
  SCRIPT_MEROITIC_HIEROGLYPHS,
  SCRIPT_MIAO,
  SCRIPT_MODI,
  SCRIPT_MONGOLIAN,
  SCRIPT_MRO,
  SCRIPT_MULTANI,
  SCRIPT_MYANMAR,
  SCRIPT_NABATAEAN,
  SCRIPT_NAG_MUNDARI,
  SCRIPT_NANDINAGARI,
  SCRIPT_NEW_TAI_LUE,
  SCRIPT_NEWA,
  SCRIPT_NKO,
  SCRIPT_NUSHU,
  SCRIPT_NYIAKENG_PUACHUE_HMONG,
  SCRIPT_OGHAM,
  SCRIPT_OL_CHIKI,
  SCRIPT_OL_ONAL,
  SCRIPT_OLD_HUNGARIAN,
  SCRIPT_OLD_ITALIC,
  SCRIPT_OLD_NORTH_ARABIAN,
  SCRIPT_OLD_PERMIC,
  SCRIPT_OLD_PERSIAN,
  SCRIPT_OLD_SOGDIAN,
  SCRIPT_OLD_SOUTH_ARABIAN,
  SCRIPT_OLD_TURKIC,
  SCRIPT_OLD_UYGHUR,
  SCRIPT_ORIYA,
  SCRIPT_OSAGE,
  SCRIPT_OSMANYA,
  SCRIPT_PAHAWH_HMONG,
  SCRIPT_PALMYRENE,
  SCRIPT_PAU_CIN_HAU,
  SCRIPT_PHAGS_PA,
  SCRIPT_PHOENICIAN,
  SCRIPT_PSALTER_PAHLAVI,
  SCRIPT_REJANG,
  SCRIPT_RUNIC,
  SCRIPT_SAMARITAN,
  SCRIPT_SAURASHTRA,
  SCRIPT_SHARADA,
  SCRIPT_SHAVIAN,
  SCRIPT_SIDDHAM,
  SCRIPT_SIGNWRITING,
  SCRIPT_SINHALA,
  SCRIPT_SOGDIAN,
  SCRIPT_SORA_SOMPENG,
  SCRIPT_SOYOMBO,
  SCRIPT_SUNDANESE,
  SCRIPT_SUNUWAR,
  SCRIPT_SYLOTI_NAGRI,
  SCRIPT_SYRIAC,
  SCRIPT_TAGALOG,
  SCRIPT_TAGBANWA,
  SCRIPT_TAI_LE,
  SCRIPT_TAI_THAM,
  SCRIPT_TAI_VIET,
  SCRIPT_TAKRI,
  SCRIPT_TAMIL,
  SCRIPT_TANGSA,
  SCRIPT_TANGUT,
  SCRIPT_TELUGU,
  SCRIPT_THAANA,
  SCRIPT_THAI,
  SCRIPT_TIBETAN,
  SCRIPT_TIFINAGH,
  SCRIPT_TIRHUTA,
  SCRIPT_TODHRI,
  SCRIPT_TOTO,
  SCRIPT_TULU_TIGALARI,
  SCRIPT_UGARITIC,
  SCRIPT_VAI,
  SCRIPT_VITHKUQI,
  SCRIPT_WANCHO,
  SCRIPT_WARANG_CITI,
  SCRIPT_YEZIDI,
  SCRIPT_YI,
  SCRIPT_ZANABAZAR_SQUARE
} script_t;

extern "C" {
    script_t get_script(uint32_t cp);
    bool grapheme_break(uint8_t* state, uint32_t cp1, uint32_t cp2);
}

inline hb_script_t script_to_hb_script(script_t script) {
  switch (script) {
    case SCRIPT_NONE: return HB_SCRIPT_UNKNOWN;
    case SCRIPT_COMMON: return HB_SCRIPT_COMMON;
    case SCRIPT_INHERITED: return HB_SCRIPT_INHERITED;
    case SCRIPT_ADLAM: return HB_SCRIPT_ADLAM;
    case SCRIPT_AHOM: return HB_SCRIPT_AHOM;
    case SCRIPT_ANATOLIAN_HIEROGLYPHS: return HB_SCRIPT_ANATOLIAN_HIEROGLYPHS;
    case SCRIPT_ARABIC: return HB_SCRIPT_ARABIC;
    case SCRIPT_ARMENIAN: return HB_SCRIPT_ARMENIAN;
    case SCRIPT_AVESTAN: return HB_SCRIPT_AVESTAN;
    case SCRIPT_BALINESE: return HB_SCRIPT_BALINESE;
    case SCRIPT_BAMUM: return HB_SCRIPT_BAMUM;
    case SCRIPT_BASSA_VAH: return HB_SCRIPT_BASSA_VAH;
    case SCRIPT_BATAK: return HB_SCRIPT_BATAK;
    case SCRIPT_BENGALI: return HB_SCRIPT_BENGALI;
    case SCRIPT_BHAIKSUKI: return HB_SCRIPT_BHAIKSUKI;
    case SCRIPT_BOPOMOFO: return HB_SCRIPT_BOPOMOFO;
    case SCRIPT_BRAHMI: return HB_SCRIPT_BRAHMI;
    case SCRIPT_BRAILLE: return HB_SCRIPT_BRAILLE;
    case SCRIPT_BUGINESE: return HB_SCRIPT_BUGINESE;
    case SCRIPT_BUHID: return HB_SCRIPT_BUHID;
    case SCRIPT_CANADIAN_ABORIGINAL: return HB_SCRIPT_CANADIAN_SYLLABICS;
    case SCRIPT_CARIAN: return HB_SCRIPT_CARIAN;
    case SCRIPT_CAUCASIAN_ALBANIAN: return HB_SCRIPT_CAUCASIAN_ALBANIAN;
    case SCRIPT_CHAKMA: return HB_SCRIPT_CHAKMA;
    case SCRIPT_CHAM: return HB_SCRIPT_CHAM;
    case SCRIPT_CHEROKEE: return HB_SCRIPT_CHEROKEE;
    case SCRIPT_CHORASMIAN: return HB_SCRIPT_CHORASMIAN;
    case SCRIPT_COPTIC: return HB_SCRIPT_COPTIC;
    case SCRIPT_CUNEIFORM: return HB_SCRIPT_CUNEIFORM;
    case SCRIPT_CYPRIOT: return HB_SCRIPT_CYPRIOT;
    case SCRIPT_CYPRO_MINOAN: return HB_SCRIPT_CYPRO_MINOAN;
    case SCRIPT_CYRILLIC: return HB_SCRIPT_CYRILLIC;
    case SCRIPT_DESERET: return HB_SCRIPT_DESERET;
    case SCRIPT_DEVANAGARI: return HB_SCRIPT_DEVANAGARI;
    case SCRIPT_DIVES_AKURU: return HB_SCRIPT_DIVES_AKURU;
    case SCRIPT_DOGRA: return HB_SCRIPT_DOGRA;
    case SCRIPT_DUPLOYAN: return HB_SCRIPT_DUPLOYAN;
    case SCRIPT_EGYPTIAN_HIEROGLYPHS: return HB_SCRIPT_EGYPTIAN_HIEROGLYPHS;
    case SCRIPT_ELBASAN: return HB_SCRIPT_ELBASAN;
    case SCRIPT_ELYMAIC: return HB_SCRIPT_ELYMAIC;
    case SCRIPT_ETHIOPIC: return HB_SCRIPT_ETHIOPIC;
    case SCRIPT_GARAY: return HB_SCRIPT_GARAY;
    case SCRIPT_GEORGIAN: return HB_SCRIPT_GEORGIAN;
    case SCRIPT_GLAGOLITIC: return HB_SCRIPT_GLAGOLITIC;
    case SCRIPT_GOTHIC: return HB_SCRIPT_GOTHIC;
    case SCRIPT_GRANTHA: return HB_SCRIPT_GRANTHA;
    case SCRIPT_GREEK: return HB_SCRIPT_GREEK;
    case SCRIPT_GUJARATI: return HB_SCRIPT_GUJARATI;
    case SCRIPT_GUNJALA_GONDI: return HB_SCRIPT_GUNJALA_GONDI;
    case SCRIPT_GURMUKHI: return HB_SCRIPT_GURMUKHI;
    case SCRIPT_GURUNG_KHEMA: return HB_SCRIPT_GURUNG_KHEMA;
    case SCRIPT_HAN: return HB_SCRIPT_HAN;
    case SCRIPT_HANGUL: return HB_SCRIPT_HANGUL;
    case SCRIPT_HANIFI_ROHINGYA: return HB_SCRIPT_HANIFI_ROHINGYA;
    case SCRIPT_HANUNOO: return HB_SCRIPT_HANUNOO;
    case SCRIPT_HATRAN: return HB_SCRIPT_HATRAN;
    case SCRIPT_HEBREW: return HB_SCRIPT_HEBREW;
    case SCRIPT_HIRAGANA: return HB_SCRIPT_HIRAGANA;
    case SCRIPT_IMPERIAL_ARAMAIC: return HB_SCRIPT_IMPERIAL_ARAMAIC;
    case SCRIPT_INSCRIPTIONAL_PAHLAVI: return HB_SCRIPT_INSCRIPTIONAL_PAHLAVI;
    case SCRIPT_INSCRIPTIONAL_PARTHIAN: return HB_SCRIPT_INSCRIPTIONAL_PARTHIAN;
    case SCRIPT_JAVANESE: return HB_SCRIPT_JAVANESE;
    case SCRIPT_KAITHI: return HB_SCRIPT_KAITHI;
    case SCRIPT_KANNADA: return HB_SCRIPT_KANNADA;
    case SCRIPT_KATAKANA: return HB_SCRIPT_KATAKANA;
    case SCRIPT_KAWI: return HB_SCRIPT_KAWI;
    case SCRIPT_KAYAH_LI: return HB_SCRIPT_KAYAH_LI;
    case SCRIPT_KHAROSHTHI: return HB_SCRIPT_KHAROSHTHI;
    case SCRIPT_KHITAN_SMALL_SCRIPT: return HB_SCRIPT_KHITAN_SMALL_SCRIPT;
    case SCRIPT_KHMER: return HB_SCRIPT_KHMER;
    case SCRIPT_KHOJKI: return HB_SCRIPT_KHOJKI;
    case SCRIPT_KHUDAWADI: return HB_SCRIPT_KHUDAWADI;
    case SCRIPT_KIRAT_RAI: return HB_SCRIPT_KIRAT_RAI;
    case SCRIPT_LAO: return HB_SCRIPT_LAO;
    case SCRIPT_LATIN: return HB_SCRIPT_LATIN;
    case SCRIPT_LEPCHA: return HB_SCRIPT_LEPCHA;
    case SCRIPT_LIMBU: return HB_SCRIPT_LIMBU;
    case SCRIPT_LINEAR_A: return HB_SCRIPT_LINEAR_A;
    case SCRIPT_LINEAR_B: return HB_SCRIPT_LINEAR_B;
    case SCRIPT_LISU: return HB_SCRIPT_LISU;
    case SCRIPT_LYCIAN: return HB_SCRIPT_LYCIAN;
    case SCRIPT_LYDIAN: return HB_SCRIPT_LYDIAN;
    case SCRIPT_MAHAJANI: return HB_SCRIPT_MAHAJANI;
    case SCRIPT_MAKASAR: return HB_SCRIPT_MAKASAR;
    case SCRIPT_MALAYALAM: return HB_SCRIPT_MALAYALAM;
    case SCRIPT_MANDAIC: return HB_SCRIPT_MANDAIC;
    case SCRIPT_MANICHAEAN: return HB_SCRIPT_MANICHAEAN;
    case SCRIPT_MARCHEN: return HB_SCRIPT_MARCHEN;
    case SCRIPT_MASARAM_GONDI: return HB_SCRIPT_MASARAM_GONDI;
    case SCRIPT_MEDEFAIDRIN: return HB_SCRIPT_MEDEFAIDRIN;
    case SCRIPT_MEETEI_MAYEK: return HB_SCRIPT_MEETEI_MAYEK;
    case SCRIPT_MENDE_KIKAKUI: return HB_SCRIPT_MENDE_KIKAKUI;
    case SCRIPT_MEROITIC_CURSIVE: return HB_SCRIPT_MEROITIC_CURSIVE;
    case SCRIPT_MEROITIC_HIEROGLYPHS: return HB_SCRIPT_MEROITIC_HIEROGLYPHS;
    case SCRIPT_MIAO: return HB_SCRIPT_MIAO;
    case SCRIPT_MODI: return HB_SCRIPT_MODI;
    case SCRIPT_MONGOLIAN: return HB_SCRIPT_MONGOLIAN;
    case SCRIPT_MRO: return HB_SCRIPT_MRO;
    case SCRIPT_MULTANI: return HB_SCRIPT_MULTANI;
    case SCRIPT_MYANMAR: return HB_SCRIPT_MYANMAR;
    case SCRIPT_NABATAEAN: return HB_SCRIPT_NABATAEAN;
    case SCRIPT_NAG_MUNDARI: return HB_SCRIPT_NAG_MUNDARI;
    case SCRIPT_NANDINAGARI: return HB_SCRIPT_NANDINAGARI;
    case SCRIPT_NEW_TAI_LUE: return HB_SCRIPT_NEW_TAI_LUE;
    case SCRIPT_NEWA: return HB_SCRIPT_NEWA;
    case SCRIPT_NKO: return HB_SCRIPT_NKO;
    case SCRIPT_NUSHU: return HB_SCRIPT_NUSHU;
    case SCRIPT_NYIAKENG_PUACHUE_HMONG: return HB_SCRIPT_NYIAKENG_PUACHUE_HMONG;
    case SCRIPT_OGHAM: return HB_SCRIPT_OGHAM;
    case SCRIPT_OL_CHIKI: return HB_SCRIPT_OL_CHIKI;
    case SCRIPT_OL_ONAL: return HB_SCRIPT_OL_ONAL;
    case SCRIPT_OLD_HUNGARIAN: return HB_SCRIPT_OLD_HUNGARIAN;
    case SCRIPT_OLD_ITALIC: return HB_SCRIPT_OLD_ITALIC;
    case SCRIPT_OLD_NORTH_ARABIAN: return HB_SCRIPT_OLD_NORTH_ARABIAN;
    case SCRIPT_OLD_PERMIC: return HB_SCRIPT_OLD_PERMIC;
    case SCRIPT_OLD_PERSIAN: return HB_SCRIPT_OLD_PERSIAN;
    case SCRIPT_OLD_SOGDIAN: return HB_SCRIPT_OLD_SOGDIAN;
    case SCRIPT_OLD_SOUTH_ARABIAN: return HB_SCRIPT_OLD_SOUTH_ARABIAN;
    case SCRIPT_OLD_TURKIC: return HB_SCRIPT_OLD_TURKIC;
    case SCRIPT_OLD_UYGHUR: return HB_SCRIPT_OLD_UYGHUR;
    case SCRIPT_ORIYA: return HB_SCRIPT_ORIYA;
    case SCRIPT_OSAGE: return HB_SCRIPT_OSAGE;
    case SCRIPT_OSMANYA: return HB_SCRIPT_OSMANYA;
    case SCRIPT_PAHAWH_HMONG: return HB_SCRIPT_PAHAWH_HMONG;
    case SCRIPT_PALMYRENE: return HB_SCRIPT_PALMYRENE;
    case SCRIPT_PAU_CIN_HAU: return HB_SCRIPT_PAU_CIN_HAU;
    case SCRIPT_PHAGS_PA: return HB_SCRIPT_PHAGS_PA;
    case SCRIPT_PHOENICIAN: return HB_SCRIPT_PHOENICIAN;
    case SCRIPT_PSALTER_PAHLAVI: return HB_SCRIPT_PSALTER_PAHLAVI;
    case SCRIPT_REJANG: return HB_SCRIPT_REJANG;
    case SCRIPT_RUNIC: return HB_SCRIPT_RUNIC;
    case SCRIPT_SAMARITAN: return HB_SCRIPT_SAMARITAN;
    case SCRIPT_SAURASHTRA: return HB_SCRIPT_SAURASHTRA;
    case SCRIPT_SHARADA: return HB_SCRIPT_SHARADA;
    case SCRIPT_SHAVIAN: return HB_SCRIPT_SHAVIAN;
    case SCRIPT_SIDDHAM: return HB_SCRIPT_SIDDHAM;
    case SCRIPT_SIGNWRITING: return HB_SCRIPT_SIGNWRITING;
    case SCRIPT_SINHALA: return HB_SCRIPT_SINHALA;
    case SCRIPT_SOGDIAN: return HB_SCRIPT_SOGDIAN;
    case SCRIPT_SORA_SOMPENG: return HB_SCRIPT_SORA_SOMPENG;
    case SCRIPT_SOYOMBO: return HB_SCRIPT_SOYOMBO;
    case SCRIPT_SUNDANESE: return HB_SCRIPT_SUNDANESE;
    case SCRIPT_SUNUWAR: return HB_SCRIPT_SUNUWAR;
    case SCRIPT_SYLOTI_NAGRI: return HB_SCRIPT_SYLOTI_NAGRI;
    case SCRIPT_SYRIAC: return HB_SCRIPT_SYRIAC;
    case SCRIPT_TAGALOG: return HB_SCRIPT_TAGALOG;
    case SCRIPT_TAGBANWA: return HB_SCRIPT_TAGBANWA;
    case SCRIPT_TAI_LE: return HB_SCRIPT_TAI_LE;
    case SCRIPT_TAI_THAM: return HB_SCRIPT_TAI_THAM;
    case SCRIPT_TAI_VIET: return HB_SCRIPT_TAI_VIET;
    case SCRIPT_TAKRI: return HB_SCRIPT_TAKRI;
    case SCRIPT_TAMIL: return HB_SCRIPT_TAMIL;
    case SCRIPT_TANGSA: return HB_SCRIPT_TANGSA;
    case SCRIPT_TANGUT: return HB_SCRIPT_TANGUT;
    case SCRIPT_TELUGU: return HB_SCRIPT_TELUGU;
    case SCRIPT_THAANA: return HB_SCRIPT_THAANA;
    case SCRIPT_THAI: return HB_SCRIPT_THAI;
    case SCRIPT_TIBETAN: return HB_SCRIPT_TIBETAN;
    case SCRIPT_TIFINAGH: return HB_SCRIPT_TIFINAGH;
    case SCRIPT_TIRHUTA: return HB_SCRIPT_TIRHUTA;
    case SCRIPT_TODHRI: return HB_SCRIPT_TODHRI;
    case SCRIPT_TOTO: return HB_SCRIPT_TOTO;
    case SCRIPT_TULU_TIGALARI: return HB_SCRIPT_TULU_TIGALARI;
    case SCRIPT_UGARITIC: return HB_SCRIPT_UGARITIC;
    case SCRIPT_VAI: return HB_SCRIPT_VAI;
    case SCRIPT_VITHKUQI: return HB_SCRIPT_VITHKUQI;
    case SCRIPT_WANCHO: return HB_SCRIPT_WANCHO;
    case SCRIPT_WARANG_CITI: return HB_SCRIPT_WARANG_CITI;
    case SCRIPT_YEZIDI: return HB_SCRIPT_YEZIDI;
    case SCRIPT_YI: return HB_SCRIPT_YI;
    case SCRIPT_ZANABAZAR_SQUARE: return HB_SCRIPT_ZANABAZAR_SQUARE;
    default: return HB_SCRIPT_UNKNOWN;
  }
}
