name: Publish
on: workflow_dispatch

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  binaries:
    name: ${{ matrix.package }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { runner: macos-15, target: aarch64-macos, package: canvas-darwin-arm64 }
          - { runner: macos-15, target: x86_64-macos, package: canvas-darwin-x64 }
          - { runner: ubuntu-latest, target: x86-windows, package: canvas-win32-x86 }
          - { runner: ubuntu-latest, target: x86_64-windows, package: canvas-win32-x64 }
          - { runner: ubuntu-latest, target: aarch64-windows, package: canvas-win32-arm64 }
          - { runner: ubuntu-latest, target: arm-linux-gnueabihf, package: canvas-linux-arm-gnueabihf }
          - { runner: ubuntu-latest, target: x86-linux-gnu.2.28, package: canvas-linux-x86-gnu }
          - { runner: ubuntu-latest, target: x86-linux-musl, package: canvas-linux-x86-musl }
          - { runner: ubuntu-latest, target: x86_64-linux-gnu.2.28, package: canvas-linux-x64-gnu }
          - { runner: ubuntu-latest, target: x86_64-linux-musl, package: canvas-linux-x64-musl }
          - { runner: ubuntu-latest, target: aarch64-linux-gnu.2.28, package: canvas-linux-arm64-gnu }
          - { runner: ubuntu-latest, target: aarch64-linux-musl, package: canvas-linux-arm64-musl }
          - { runner: ubuntu-latest, target: riscv64-linux-gnu, package: canvas-linux-riscv64-gnu }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds
      - uses: mlugg/setup-zig@v2
      - name: Install
        run: npm ci --force # https://github.com/npm/cli/issues/6138
      - name: Build
        run: zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseSafe
      - name: Publish
        run: npm publish --workspace ${{ matrix.package }} --tag next

  root:
    name: canvas
    needs: binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26
      - name: Install
        run: npm ci --force # https://github.com/npm/cli/issues/6138
      - name: Publish
        run: npm publish --dry-run
